### ISSUE TITLE
Maven repository is not up-to-date with the last version

### ISSUE THREAD

**Issue by nathanagez** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#190]
Hi there, I wanted to use the SDK as a dependency of a Maven project so I imported the library like following:

```xml
        <!-- https://mvnrepository.com/artifact/com.amazonaws/amazon-kinesis-video-streams-producer-sdk-java -->
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>amazon-kinesis-video-streams-producer-sdk-java</artifactId>
            <version>1.12.0</version>
        </dependency>
```

However, I noticed that Maven Central doesn't have the last version of the library which is `1.12.1` (on 12/20/23). 
Is it something wanted on your side to don't maintain Maven up-to-date with the sources ? 

I would like to use the last version because version 1.12.0 throw the following errors (even if we receive data on Kinesis at the end):

```
2023-12-20 08:41:37 WARN    setClientInfo(): Couldn't find method id getAutomaticStreamingFlags
Exception in thread "main" java.lang.NoSuchMethodError: getAutomaticStreamingFlags
	at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoClient(Native Method)
	at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.create(NativeKinesisVideoProducerJni.java:234)
	at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createSync(NativeKinesisVideoProducerJni.java:246)
	at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createSync(NativeKinesisVideoProducerJni.java:211)
	at com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.initializeNewKinesisVideoProducer(NativeKinesisVideoClient.java:239)
	at com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.initialize(NativeKinesisVideoClient.java:119)
	at com.amazonaws.kinesisvideo.java.client.KinesisVideoJavaClientFactory.createKinesisVideoClient(KinesisVideoJavaClientFactory.java:111)
	at com.amazonaws.kinesisvideo.java.client.KinesisVideoJavaClientFactory.createKinesisVideoClient(KinesisVideoJavaClientFactory.java:84)
	at com.trackit.Main.main(Main.java:42)
2023-12-20 09:41:37,719 [main] ERROR c.a.k.j.c.KinesisVideoJavaClientFactory - [PIC] KinesisVideoClientWrapper - logPrintFunc(): JVM threw an unexpected exception.
2023-12-20 09:41:37,752 [main] WARN  c.a.k.j.c.KinesisVideoJavaClientFactory - [PIC] KinesisVideoParametersConversion - setStreamInfo(): Couldn't find method id getStorePressurePolicy
Exception in thread "main" java.lang.NoSuchMethodError: getStorePressurePolicy
	at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoStream(Native Method)
	at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createStream(NativeKinesisVideoProducerJni.java:324)
	at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createStreamSync(NativeKinesisVideoProducerJni.java:351)
	at com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.registerMediaSource(NativeKinesisVideoClient.java:131)
	at com.trackit.Main.main(Main.java:54)
2023-12-20 09:41:37,753 [main] ERROR c.a.k.j.c.KinesisVideoJavaClientFactory - [PIC] KinesisVideoClientWrapper - logPrintFunc(): JVM threw an unexpected exception.
2023-12-20 09:41:38,537 [KVS-JavaClientExecutor-1] WARN  c.a.k.j.c.KinesisVideoJavaClientFactory - [PIC] StreamEvent - describeStreamResult(): Retention period returned from the DescribeStream call doesn't match the one specified in the StreamInfo
2023-12-20 09:41:38,538 [KVS-JavaClientExecutor-1] WARN  c.a.k.j.c.KinesisVideoJavaClientFactory - [PIC] StreamEvent - describeStreamResult(): Content type returned from the DescribeStream call doesn't match the one specified in the StreamInfo
```

Thank you.

**Comment by hassanctech** [comment]
Hi @nathanagez, apologies for the late response here.  It appears there was a miss on our part and this was not released to maven.  Since this release is already 2 years ago, we will investigate if we want to release this to maven now, or cut a new release and then release that to maven.  We will update here shortly.
